### ISSUE TITLE
Auto geração dos scripts de instalação a partir do Org

### ISSUE THREAD

**Issue by yuhribernardes** [araujorafael/dotfiles#2]
Se vc deixar mais automatizado os scripts pra ter a menor quantidade de iteração humana possível, da pra gerar um arquivo de script a partir do seu org mode.
Se vc adicionar
```org
#+TITLE: Some title
#+AUTHOR: Your name
#+PROPERTY: header-args :tangle file/to/my/path
```
E rodar `M-x org-babel-tangle` ele vai pegar seus blocos de SRC e colocar tudo em sequencia no arquivo que vc nomeou na `PROPERTY`.

Exemplo:

```org
#+TITLE: ZSH Configuration
#+AUTHOR: Yuhri Graziano Bernardes
#+PROPERTY: header-args :tangle ~/.zshrc
```

Ao rodar o comando ele vai pegar todos os códigos e jogar no meu `~/.zshrc`

**Comment by araujorafael** [comment]
Isso é interessante dá para fzer um "scripto" gigantaã de instalação.

**Comment by YuhriBernardes** [comment]
Yep, e ainda manter o tracking do que cada script faz com uma descrição descente

**Comment by YuhriBernardes** [comment]
![image](https://user-images.githubusercontent.com/38089687/89344779-cc4b5800-d67c-11ea-95fa-0c44ecd31a8f.png)
