### ISSUE TITLE
Utilização do repositorio como Bare Repository

### ISSUE THREAD

**Issue by YuhriBernardes** [araujorafael/dotfiles#3]
Recomendo que assista esse [video](https://youtu.be/tBoLDpTWVOM)
To usando essa abordagem e ta valendo muito a pena (não sei se já não está utilizando)

[Meu Repo](https://github.com/YuhriBernardes/dotfiles) | [Artigo da atlassian sobre isso](https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/)

**Comment by araujorafael** [comment]
Verdade, isso é algo que preciso fazer urgente.

**Comment by YuhriBernardes** [comment]
Acho que vc também pode dar uma olhada nesse blog post também. Achei dahora. To pensando em experimentar

[Interactive dotfile management with dotbare](https://www.distrotube.com/blog/interactive-dotfiles-management-with-dotbare/)

**Comment by araujorafael** [comment]
Fiz o commit direto na master e e fiz como bare... ficou bem mais simples. Vlw @YuhriBernardes
